@HOST=http://localhost:3000

GET {{HOST}}/api/students 

###
POST {{HOST}}/api/students
Content-Type: application/json

{
    "name":"Pepe",
    "surname": "Velázquez",
    "phone": "7654321",
    "email":"pepeG@gmail.com"
}

###
POST {{HOST}}/api/teachers
Content-Type: application/json

{
    "first_name":"Ana",
    "last_name": "García",
    "age": 32,
    "available": true,
}